// -----------------------------------------------------------------------------
// ALERTS — modelled on CAP v1.2 (Common Alerting Protocol, OASIS standard)
// -----------------------------------------------------------------------------
// Every alert in this file is SYNTHETIC. Nothing here came from IMD, CWC, INCOIS
// or NDMA's Sachet system, and this prototype is not connected to any of them.
//
// The SHAPE, however, is deliberately real. CAP v1.2 is the format Sachet
// already emits and the format IMD, CWC and INCOIS already publish in. Modelling
// the synthetic data on the true schema is what makes the claim on /how-it-runs
// checkable rather than aspirational: swapping this array for a live CAP feed is
// a parser change, not a redesign. Field names below map 1:1 to CAP elements.
//
//   identifier / sender / sent / status / msgType / scope   → <alert>
//   category / event / urgency / severity / certainty       → <info>
//   effective / onset / expires / instruction               → <info>
//   areaDesc / geocode / polygon                            → <area>
// -----------------------------------------------------------------------------

import type { HazardType, LangCode } from "./districts";

/** CAP <severity>. Mapped to the four-level citizen scale in level(). */
export type CapSeverity = "Extreme" | "Severe" | "Moderate" | "Minor";
/** CAP <urgency>. */
export type CapUrgency = "Immediate" | "Expected" | "Future" | "Past";
/** CAP <certainty>. */
export type CapCertainty = "Observed" | "Likely" | "Possible" | "Unlikely";

/** The citizen-facing scale. Four levels, because five is one more than anyone
 *  can hold under stress and three cannot separate "get ready" from "go now".
 *  Structure follows Japan's five-level system collapsed at the top: their
 *  Levels 4 and 5 are both "evacuate", and the distinction between them has been
 *  shown to cost time. Documented on /how-it-runs. */
export type Level = 1 | 2 | 3 | 4;

export interface Alert {
  /** CAP <identifier>. Format mirrors Sachet's: SENDER.YYYY.NNNN */
  identifier: string;
  /** CAP <sender>. Synthetic sender IDs in the real agencies' namespace shape. */
  sender: string;
  senderName: string;
  /** CAP <sent>, ISO 8601. Relative to app load — see resolveTimes(). */
  sentOffsetMin: number;
  /** CAP <onset> — when impact begins. Minutes from load. Null = already begun. */
  onsetOffsetMin: number | null;
  /** CAP <expires>. Minutes from load. */
  expiresOffsetMin: number;

  status: "Actual" | "Exercise" | "Test";
  msgType: "Alert" | "Update" | "Cancel";
  scope: "Public";

  category: "Met" | "Geo" | "Safety" | "Fire" | "Health";
  event: string;
  hazard: HazardType;
  urgency: CapUrgency;
  severity: CapSeverity;
  certainty: CapCertainty;

  districtId: string;
  areaDesc: string;

  /** CAP <headline>. Kept under 60 chars — it has to survive an SMS and a
   *  lock-screen notification without truncating mid-word. */
  headline: string;
  /** CAP <description>. Written the way the source agency writes: precise,
   *  technical, and not actionable by itself. This is the input to /api/plain. */
  description: string;
  /** CAP <instruction>. The ordered actions. Never generated by a model —
   *  see lib/rules.ts. */
  instruction: string[];
  /** Things NOT to do. The original portal buried these; they are the actions
   *  that actually kill people (driving through water, using lifts). */
  avoid: string[];

  /** CAP <parameter> — the measured quantity, if the hazard has one. This is
   *  the number that makes a warning checkable instead of atmospheric. */
  measure?: { label: string; value: string; threshold: string; trend?: string };

  /** Whether a shelter list is relevant for this alert. */
  shelters: boolean;
}

// -----------------------------------------------------------------------------

export function level(a: Pick<Alert, "severity" | "urgency">): Level {
  if (a.severity === "Extreme" && a.urgency === "Immediate") return 4;
  if (a.severity === "Extreme" || a.severity === "Severe") return 3;
  if (a.severity === "Moderate") return 2;
  return 1;
}

export const LEVEL_META: Record<Level, { key: string; tone: string; band: string }> = {
  4: { key: "l4", tone: "l4", band: "EVACUATE NOW" },
  3: { key: "l3", tone: "l3", band: "BE PREPARED" },
  2: { key: "l2", tone: "l2", band: "STAY ALERT" },
  1: { key: "l1", tone: "l1", band: "FOR INFORMATION" },
};

// -----------------------------------------------------------------------------
// The synthetic national feed.
// -----------------------------------------------------------------------------

export const ALERTS: Alert[] = [
  {
    identifier: "CWC-GHY.2026.0417",
    sender: "cwc.brahmaputra@synthetic.invalid",
    senderName: "Central Water Commission — Brahmaputra Division",
    sentOffsetMin: -12, onsetOffsetMin: 120, expiresOffsetMin: 720,
    status: "Actual", msgType: "Alert", scope: "Public",
    category: "Met", event: "Severe Flood", hazard: "flood",
    urgency: "Immediate", severity: "Extreme", certainty: "Observed",
    districtId: "golaghat", areaDesc: "Golaghat district, Assam — Dhansiri left bank",
    headline: "Dhansiri above danger mark — leave low ground now",
    description:
      "River Dhansiri at Numaligarh gauge reading 79.42 m against a danger level of 78.60 m, rising at 11 cm/hr over the last three observations. Inflow from upper catchment continues. Left bank embankment at Ch. 14.2 km reported under strain. Inundation of low-lying revenue villages expected within 2 hours.",
    instruction: [
      "Leave for higher ground now. Do not wait for water to reach your door.",
      "Take drinking water, any daily medicines, and your ID papers in a sealed bag.",
      "Switch off the main electricity switch before you leave.",
      "Tell one neighbour which way you are going.",
    ],
    avoid: [
      "Do not walk or drive through moving water. Knee-deep water moves a car.",
      "Do not go back for belongings once you have left.",
      "Do not wait for a second warning. There may not be one.",
    ],
    measure: { label: "Dhansiri at Numaligarh", value: "79.42 m", threshold: "danger 78.60 m", trend: "rising 11 cm/hr" },
    shelters: true,
  },
  {
    identifier: "IMD-BBS.2026.1180",
    sender: "imd.cyclone.bbsr@synthetic.invalid",
    senderName: "India Meteorological Department — Cyclone Warning Division",
    sentOffsetMin: -35, onsetOffsetMin: 1440, expiresOffsetMin: 2880,
    status: "Actual", msgType: "Update", scope: "Public",
    category: "Met", event: "Cyclone Warning", hazard: "cyclone",
    urgency: "Expected", severity: "Severe", certainty: "Likely",
    districtId: "puri", areaDesc: "Puri district, Odisha — coastal belt and fishing harbours",
    headline: "Cyclone landfall expected near Puri in 24 hours",
    description:
      "Depression over west-central Bay of Bengal intensified into a cyclonic storm, centred approximately 470 km south-east of Puri, moving north-northwest at 14 km/h. Landfall expected between Puri and Satabhaya as a severe cyclonic storm with sustained winds of 100–110 km/h gusting to 120 km/h. Storm surge of 1.2–1.5 m above astronomical tide likely in low-lying coastal areas.",
    instruction: [
      "Move to a cyclone shelter today, not tomorrow. Roads close before landfall.",
      "Charge every phone and power bank now.",
      "Fill drinking water containers. Piped supply usually stops.",
      "Fishermen must return to harbour and not put to sea.",
    ],
    avoid: [
      "Do not go outside during the calm eye. The wind returns from the other side.",
      "Do not shelter under a tin roof or near a hoarding.",
      "Do not stay in a kutcha house on the coastal strip.",
    ],
    measure: { label: "Sustained wind at landfall", value: "100–110 km/h", threshold: "gusting 120 km/h", trend: "storm surge 1.2–1.5 m" },
    shelters: true,
  },
  {
    identifier: "IMD-TVM.2026.0902",
    sender: "imd.kerala@synthetic.invalid",
    senderName: "India Meteorological Department — Thiruvananthapuram",
    sentOffsetMin: -58, onsetOffsetMin: 240, expiresOffsetMin: 1440,
    status: "Actual", msgType: "Alert", scope: "Public",
    category: "Met", event: "Heavy Rain Watch", hazard: "flood",
    urgency: "Expected", severity: "Moderate", certainty: "Likely",
    districtId: "wayanad", areaDesc: "Wayanad district, Kerala — hill blocks",
    headline: "Very heavy rain likely over Wayanad hill blocks",
    description:
      "Isolated very heavy rainfall of 115–160 mm in 24 hours likely over Wayanad on account of an offshore trough. Soil moisture in the district is already at 92% of capacity following four consecutive wet days.",
    instruction: [
      "Avoid travel on hill roads for the next 24 hours.",
      "Keep torches and a charged phone within reach tonight.",
      "If you live below a steep slope, sleep on the road-facing side of the house.",
    ],
    avoid: [
      "Do not park below a cut slope.",
      "Do not cross a stream that has turned brown, even if it looks shallow.",
    ],
    measure: { label: "Forecast rainfall", value: "115–160 mm/24h", threshold: "very heavy ≥115 mm", trend: "soil moisture 92%" },
    shelters: false,
  },
  {
    identifier: "GSI-DDN.2026.0233",
    sender: "gsi.landslide.uk@synthetic.invalid",
    senderName: "Geological Survey of India — Landslide Early Warning, Uttarakhand",
    sentOffsetMin: -21, onsetOffsetMin: 0, expiresOffsetMin: 960,
    status: "Actual", msgType: "Alert", scope: "Public",
    category: "Geo", event: "Landslide Warning", hazard: "landslide",
    urgency: "Immediate", severity: "Severe", certainty: "Likely",
    districtId: "chamoli", areaDesc: "Chamoli district, Uttarakhand — NH-7 corridor, Pipalkoti to Joshimath",
    headline: "Slopes unstable on NH-7 — roads may close without notice",
    description:
      "Cumulative rainfall of 214 mm over 72 hours has exceeded the intensity-duration threshold for slope failure on the Pipalkoti–Joshimath stretch. Three minor debris flows recorded in the last 12 hours. Further failures likely without additional rainfall.",
    instruction: [
      "Do not begin a hill journey today. If you are on the road, stop at the next town.",
      "Move your vehicle away from the base of any cut slope.",
      "Keep two days of food and water at home. The road may close in both directions.",
    ],
    avoid: [
      "Do not park or stand below a steep slope, even briefly.",
      "Do not try to drive through fresh debris. More usually follows.",
      "Do not rely on a road being open because it was open an hour ago.",
    ],
    measure: { label: "Rainfall, 72 hours", value: "214 mm", threshold: "failure threshold 180 mm", trend: "3 debris flows in 12 h" },
    shelters: true,
  },
  {
    identifier: "NCS-DEL.2026.0064",
    sender: "ncs.seismology@synthetic.invalid",
    senderName: "National Center for Seismology",
    sentOffsetMin: -95, onsetOffsetMin: null, expiresOffsetMin: 2160,
    status: "Actual", msgType: "Update", scope: "Public",
    category: "Geo", event: "Aftershock Watch", hazard: "earthquake",
    urgency: "Expected", severity: "Moderate", certainty: "Possible",
    districtId: "shimla", areaDesc: "Shimla district, Himachal Pradesh",
    headline: "Aftershocks possible after yesterday's M4.2 tremor",
    description:
      "A magnitude 4.2 event was recorded at 19:41 IST yesterday at a depth of 10 km, 34 km north-east of Shimla. Twelve aftershocks between M1.8 and M2.9 have been recorded since. Aftershocks of up to M3.5 remain possible for 72 hours.",
    instruction: [
      "Keep the path from your bed to the door clear tonight.",
      "Keep shoes and a torch beside your bed.",
      "If shaking starts: drop, cover under something sturdy, and hold on.",
    ],
    avoid: [
      "Do not use lifts for the next two days.",
      "Do not run outside while the ground is still moving. Most injuries happen in doorways and stairwells.",
    ],
    measure: { label: "Main event", value: "M4.2", threshold: "depth 10 km", trend: "12 aftershocks recorded" },
    shelters: false,
  },
  {
    identifier: "IMD-NGP.2026.0771",
    sender: "imd.vidarbha@synthetic.invalid",
    senderName: "India Meteorological Department — Nagpur",
    sentOffsetMin: -140, onsetOffsetMin: 180, expiresOffsetMin: 1080,
    status: "Actual", msgType: "Alert", scope: "Public",
    category: "Health", event: "Heatwave Alert", hazard: "heatwave",
    urgency: "Expected", severity: "Severe", certainty: "Likely",
    districtId: "nagpur", areaDesc: "Nagpur district, Maharashtra",
    headline: "Severe heatwave — peak danger 12 PM to 4 PM",
    description:
      "Maximum temperature expected to reach 45.8 °C against a normal of 39.2 °C for this date, a departure of +6.6 °C. Night minimum not falling below 30 °C, which removes the overnight recovery period and is the stronger predictor of heat mortality.",
    instruction: [
      "Drink water every hour, even when you do not feel thirsty.",
      "Stay indoors between 12 PM and 4 PM.",
      "Check on anyone over 65 or living alone, twice today.",
      "If someone stops sweating and becomes confused, that is heatstroke. Call 108.",
    ],
    avoid: [
      "Do not leave anyone, or any animal, inside a parked vehicle.",
      "Do not do outdoor physical work in the afternoon.",
      "Do not drink alcohol, or very sugary drinks, to cool down.",
    ],
    measure: { label: "Forecast maximum", value: "45.8 °C", threshold: "normal 39.2 °C", trend: "departure +6.6 °C" },
    shelters: false,
  },
  {
    identifier: "IMD-GHY.2026.0588",
    sender: "imd.assam@synthetic.invalid",
    senderName: "India Meteorological Department — Guwahati",
    sentOffsetMin: -47, onsetOffsetMin: 300, expiresOffsetMin: 600,
    status: "Actual", msgType: "Alert", scope: "Public",
    category: "Met", event: "Thunderstorm Advisory", hazard: "thunderstorm",
    urgency: "Expected", severity: "Moderate", certainty: "Likely",
    districtId: "guwahati", areaDesc: "Kamrup Metropolitan district, Assam",
    headline: "Lightning and gusty winds likely this evening",
    description:
      "Thunderstorm with lightning and gusty winds of 40–50 km/h likely between 17:00 and 21:00 IST. Assam records among the highest lightning-strike fatality rates in the country, and the large majority occur outdoors.",
    instruction: [
      "Be indoors between 5 PM and 9 PM if you can.",
      "If you are caught outside, crouch low. Do not lie flat and do not stand under a tree.",
      "Unplug appliances you care about.",
    ],
    avoid: [
      "Do not shelter under an isolated tree. That is where most strikes kill.",
      "Do not stand in an open field or on a rooftop.",
    ],
    measure: { label: "Gust speed", value: "40–50 km/h", threshold: "advisory ≥40 km/h", trend: "window 17:00–21:00 IST" },
    shelters: false,
  },
  {
    identifier: "IMD-JDH.2026.0311",
    sender: "imd.rajasthan@synthetic.invalid",
    senderName: "India Meteorological Department — Jodhpur",
    sentOffsetMin: -320, onsetOffsetMin: null, expiresOffsetMin: 4320,
    status: "Actual", msgType: "Update", scope: "Public",
    category: "Met", event: "Drought Watch", hazard: "drought",
    urgency: "Future", severity: "Minor", certainty: "Likely",
    districtId: "jodhpur", areaDesc: "Jodhpur district, Rajasthan",
    headline: "Rainfall 41% below normal this season",
    description:
      "Cumulative seasonal rainfall stands at 118 mm against a normal of 200 mm, a deficiency of 41%. Three of seven reservoir gauges in the district are below 30% of live capacity.",
    instruction: [
      "Plan for reduced piped supply over the coming weeks.",
      "Check with your gram panchayat about tanker schedules before you need one.",
    ],
    avoid: ["Do not depend on a single water source for the season."],
    measure: { label: "Seasonal rainfall", value: "118 mm", threshold: "normal 200 mm", trend: "deficiency 41%" },
    shelters: false,
  },
];

/** Alerts affecting a district, most severe first. */
export function alertsFor(districtId: string): Alert[] {
  return ALERTS.filter((a) => a.districtId === districtId)
    .sort((a, b) => level(b) - level(a));
}

/** The single alert that should own the screen for a district, if any. */
export function topAlert(districtId: string): Alert | null {
  return alertsFor(districtId)[0] ?? null;
}

export const HAZARD_LABEL: Record<HazardType, string> = {
  flood: "Flood", "urban-flood": "Urban flooding", cyclone: "Cyclone",
  earthquake: "Earthquake", landslide: "Landslide", heatwave: "Heatwave",
  thunderstorm: "Thunderstorm", drought: "Drought", wildfire: "Wildfire",
  coldwave: "Cold wave",
};

/** Language coverage of the real upstream systems, used to state the gap.
 *  Sachet and IMD bulletins are issued in English and Hindi. */
export const UPSTREAM_LANGUAGES: LangCode[] = ["en", "hi"];

// -----------------------------------------------------------------------------
// POPULATION UNDER A WARNING
// -----------------------------------------------------------------------------
// Borrowed from BhimShila (github.com/CyNoGeN1109/bhimshila), which ranks live
// Sachet alerts by how many people are actually underneath each one. It is the
// best idea in the Indian disaster-tooling field right now and it costs us
// almost nothing, because district population is already in the dataset.
//
// The reason it matters: a warning feed sorted by severity alone tells a reader
// that four things are Level 3. It does not tell them that one of those covers
// nine million people and another covers eight thousand. Severity is a property
// of the hazard; exposure is a property of the people. Ranking on severity and
// then on exposure is closer to how a district control room actually triages.
//
// The number here is the district's whole 2011 Census population, which is a
// CEILING, not an estimate of who is in the hazard footprint — a river warning
// does not threaten everyone in the district. It is labelled that way on screen
// rather than being presented as a casualty projection.
// -----------------------------------------------------------------------------

import { DISTRICT_BY_ID } from "./districts";

export function populationUnder(a: Alert): number {
  return DISTRICT_BY_ID[a.districtId]?.pop ?? 0;
}

/** Severity first, then exposure. Never exposure first: a Level 4 over a small
 *  district still outranks a Level 2 over a city, because the level is a
 *  statement about what is about to happen to the people who are there. */
export function rankAlerts(list: Alert[]): Alert[] {
  return [...list].sort((x, y) => {
    const lv = level(y) - level(x);
    if (lv !== 0) return lv;
    return populationUnder(y) - populationUnder(x);
  });
}

/** Total population under every alert at or above a level. Used on /how-it-runs
 *  to make the scale of the feed concrete. */
export function populationAtOrAbove(lv: Level): number {
  return ALERTS.filter((a) => level(a) >= lv).reduce((n, a) => n + populationUnder(a), 0);
}

/** "9.4 million" / "8,100" — a number a person can hold, not 9429408. */
export function formatPeople(n: number): string {
  if (n >= 10_000_000) return `${(n / 10_000_000).toFixed(1)} crore`;
  if (n >= 100_000) return `${(n / 100_000).toFixed(1)} lakh`;
  return n.toLocaleString("en-IN");
}
